### PR TITLE
weighted least squares support

### PR DESCRIPTION
**Pull request by devel-chm**
I just got basic weighted least squares support in my fork of SavitzkyGolay.jl.

As part of the development I added some basic unit tests to avoid any
regressions from the released version.

I'm planning to add some doc strings and update the README.md.  I
haven't had time because I need to get to using the new SG weights.

I'm sending a pull request to get more eyes on the code, suggestions,
and what not.  It should be backward compatible to the existing 0.7.0
release but the only tests I have are the 2 from the README examples.

### CODE REVIEW

**Comment by langestefan** [comment]
Great work. I had the same idea: https://github.com/lnacquaroli/SavitzkyGolay.jl/issues/29

What about supporting [any of the windows from DSP.jl](https://docs.juliadsp.org/stable/windows/) as a valid weight vector?

In particular the triangular window yields very good results (see article linked in the issue above). And there is also an 'optimal' weight vector, see this [mathworks article](https://nl.mathworks.com/help/signal/ug/design-and-analysis-of-savitzky-golay-filters.html), section 'Optimal Weights with Optimal Smoothness'.

**Comment by devel-chm** [comment]
> Great work. I had the same idea: #29

Thanks, I did see your issue when I got to the point of wanting
to upstream my additions to the code.

> What about supporting [any of the windows from DSP.jl](https://docs.juliadsp.org/stable/windows/) as a valid weight vector?

The references I followed, [including wikipedia](https://en.wikipedia.org/wiki/Savitzky%E2%80%93Golay_filter#Weighting_the_data), had the requirement that
the weights be positive.  I'm not sure if it is valid or useful to have a non-positive
weight value(s).
 
> In particular the triangular window yields very good results (see article linked in the issue above). And there is also an 'optimal' weight vector, see this [mathworks article](https://nl.mathworks.com/help/signal/ug/design-and-analysis-of-savitzky-golay-filters.html), section 'Optimal Weights with Optimal Smoothness'.

Yes, thanks for the reference.  I ended up using a triangle window as my
test case.

**Comment by langestefan** [comment]
> The references I followed, [including wikipedia](https://en.wikipedia.org/wiki/Savitzky%E2%80%93Golay_filter#Weighting_the_data), had the requirement that
> the weights be positive. I'm not sure if it is valid or useful to have a non-positive
> weight value(s).

I'm not really sure what you mean. All the windows in DSP.jl meet that requirement

**Comment by devel-chm** [comment]
The weight function cannot be zero.

A lot of the windowing functions go to zero so care must
be taken (usually at the edges) so the values are positive.

**Review by lnacquaroli — APPROVED** [review]
Looks good. Regarding the tests, if you find more to add to make it more confident, feel free to do so. Thanks!

**Comment by lnacquaroli** [comment]
Update the README please as well and go on with the merge.

**Comment by lnacquaroli** [comment]
The purpose of DSP.jl is much broader than this package. The reason for the SG here to exist was to have a quick and easy implementation that doesn't rely on heavy dependencies. I'm OK with improving it, but making something similar to what exists wouldn't seem useful.

**Comment by langestefan** [comment]
> The purpose of DSP.jl is much broader than this package. The reason for the SG here to exist was to have a quick and easy implementation that doesn't rely on heavy dependencies. I'm OK with improving it, but making something similar to what exists wouldn't seem useful.

I would only use DSP.jl to define the windows since it has very good functionality for that. If you're going to use a SavitzkyGolay filter there is a 99% chance you area already using DSP.jl. The alternative would be to let the user supply the weights, but then they have to do the window sampling themselves

**Comment by devel-chm** [comment]
I've updated the README and synchronized examples.  I wasn't able to make another pull request.  The current main head of my fork should be good to go.  You'll need to update the image link paths for your repository.  I don't know if there is an easier way to automate that.

**Comment by devel-chm** [comment]
Closing to try another pull request.

**Pull request closed without merging**
